### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by zen0bit** [nwestfal/pylotro#11]
I am trying to use pylotro for ddo installed through steam on void linux but...
python3-PyQt4 installed, tried also with python2
output:
Traceback (most recent call last):
  File "/usr/bin/pylotro", line 31, in <module>
    import PyLotROLauncher.Runner
  File "/usr/lib/python3.8/site-packages/PyLotROLauncher/Runner.py", line 30, in <module>
    from .MainWindow import MainWindow
  File "/usr/lib/python3.8/site-packages/PyLotROLauncher/MainWindow.py", line 34, in <module>
    from PyQt4 import QtCore, QtGui, uic
ModuleNotFoundError: No module named 'PyQt4'

Any advice?
Thanks

**Comment by nwestfal** [comment]
Hi, I just had this exact problem on OpenSUSE Tumbleweed after an upgrade.
The problem was that Python was upgraded to 3.8 but python3-qt4 was not and
still built against Python 3.7.  I had to rebuild it from source rpm
packages so that it was linked to Python 3.8.  Hope this helps!

**Comment by JeremyStepp** [comment]
I have a continuation project of PyLotro that might be easier for you to use. Along with many new features it was upgraded to PyQt5 and more recently PySide2, so you shouldn't have any dependency issues. You can find it [here](https://github.com/JeremyStepp/OneLauncher) . I think you may also be able to use Anaconda to get the right versions of libraries for PyLotro.

**Comment by JeremyStepp** [comment]
@nwestfal Updating to PyQt5 was one of the first things I did, so it should be pretty easy for you to translate the commits over. Here are the original commits if you're interested:
* https://github.com/JeremyStepp/OneLauncher/commit/23f7e16e1662df84f2e81120b80211fbc9e057c4
* https://github.com/JeremyStepp/OneLauncher/commit/e3d39d7c500dc1351eb51fa7e17ee11186891e9d
* https://github.com/JeremyStepp/OneLauncher/commit/e835f2b2a415df39f06ee89ee65d6b0723d58572
* https://github.com/JeremyStepp/OneLauncher/commit/da4aa31e42c71c1cb7c459d30b2c27265f33922c
* https://github.com/JeremyStepp/OneLauncher/commit/0b6831f453ca14c920118b70b4a60888acf8b8d9
* https://github.com/JeremyStepp/OneLauncher/commit/8480c6196073bd07b7b3fa0ec20a97442a65cd10

**Comment by nwestfal** [comment]
Thanks Jeremy will definitely work on those changes as time permits!
